on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build firmware
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: linter
      run: |
        pip install cpplint
        for project in carl calibrate; do
          make -C "$project" lint
        done

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: install platformio
      run: |
        pip install platformio==6.1.9

    - name: build calibrate firmware
      run: |
        export PLATFORMIO_BUILD_DIR=$HOME/build-calibrate
        make -C calibrate ci

    - name: build carl firmware
      run: |
        export PLATFORMIO_BUILD_DIR=$HOME/build-carl
        make -C carl ci
        mkdir -p firmware
        cp $PLATFORMIO_BUILD_DIR/pro16MHzatmega328-makuna/firmware.hex firmware/

    - name: upload carl artifacts
      uses: actions/upload-artifact@master
      with:
        name: firmware
        path: firmware/

